rstudio-workbench:
  launcher:
    enabled: false
  license:
    file:
      contents: |
        changeme
  pod:
    env:
      - name: WORKBENCH_POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rstudio-workbench-database
            key: password
  homeStorage:
    name: "pwb-pwb-subchart-pvc"
    mount: true
  userCreate: true
# Persistent Volume Claim configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # storageClass: ""  # Use default storage class if not specified