launcher:
  enabled: false
license:
  file:
    secret: rstudio-workbench-license
    secretKey: license.lic
pod:
  env:
    - name: WORKBENCH_POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: rstudio-workbench-database
          key: password

# Persistent Volume Claim configuration
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # storageClass: ""  # Use default storage class if not specified
homeStorage:
  name: "pwb-pwb-subchart-pvc"
  mount: true
userCreate: true